name: Android Unit Tests

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: '33.0.2'
          target: android-33
          ndk: '25.2.9519653'

      # Accept Android licenses
      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      # Build the project (optional but recommended)
      - name: Assemble Debug Build
        run: ./gradlew assembleDebug --stacktrace

      # Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace

      # Upload test report if it exists
      - name: Upload Test Report
        if: success() && hashFiles('app/build/reports/tests/testDebugUnitTest/index.html') != ''
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/reports/tests/testDebugUnitTest/
